server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:~/local-db:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      # oneToMany시에 in query 자동 작성
      default_batch_fetch_size: 100
    # db session controller까지 가져오기
    open-in-view: false
  # hibernateLazyInitializer 오류 해결법
  # jackson:
  #  serialization:
  #    fail-on-empty-beans: false

  # multipart 사이즈 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    '[shop.mtcoding.restend]': DEBUG # DEBUG 레벨부터 에러 확인할 수 있게 설정하기
    '[org.hibernate.type]': TRACE # 콘솔 쿼리에 ? 에 주입된 값 보기


# S3 버킷 설정 (AWS)
cloud:
  aws:
    credentials:
      accessKey: ${aws.access.key}
      secretKey: ${aws.secret.key}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ${aws.s3.bucket}
      #url: ${aws.s3.bucket.url}

sentry:
  dsn: https://1a0da37591cc45e79c99516ec086db2a@o4505186712223744.ingest.sentry.io/4505188161290240
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  release: 23.05.16
  environment: dev