server:
  port: 5999
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      default_batch_fetch_size: 100
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    # multipart 사이즈 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    '[shop.mtcoding.restend]': INFO # DEBUG 레벨부터 에러 확인할 수 있게 설정하기

file:
  path: ./upload/ # UPLOAD 폴더 상대경로 / AWS에 S3 사용하는게 좋음
# S3 버킷 설정 (AWS)
cloud:
  aws:
    credentials:
      accessKey: ${aws.access.key}
      secretKey: ${aws.secret.key}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ${aws.s3.bucket}
      #url: ${aws.s3.bucket.url}
sentry:
  dsn: https://1a0da37591cc45e79c99516ec086db2a@o4505186712223744.ingest.sentry.io/4505188161290240
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0