:event: event-controller-test
:snippets: ./build/generated-snippets
[[연차당직-API]]
== 연차/당직 API

=== 연차 신청 (성공)
// operation::user-controller-test/join_success_test[snippets='http-request,request-fields,http-response,response-fields']
operation::{event}/event_add_annual_test[snippets='http-request,http-response,curl-request']

=== 연차 신청 (실패)
// operation::user-controller-test/join_success_test[snippets='http-request,request-fields,http-response,response-fields']
operation::{event}/event_add_annual_fail_test[snippets='http-request,http-response,curl-request']

=== 당직 신청 (성공)
// operation::user-controller-test/join_success_test[snippets='http-request,request-fields,http-response,response-fields']
operation::{event}/event_add_duty_test[snippets='http-request,http-response,curl-request']

=== 당직 신청 (실패)
// operation::user-controller-test/join_success_test[snippets='http-request,request-fields,http-response,response-fields']
operation::{event}/event_add_duty_fail_test[snippets='http-request,http-response,curl-request']

=== 신청한 연차 수정
operation::{event}/event_modify_annual_test[snippets='http-request,http-response,curl-request']

=== 신청한 당직 수정
operation::{event}/event_modify_duty_test[snippets='http-request,http-response,curl-request']


=== 연차 취소
// operation::user-controller-test/join_success_test[snippets='http-request,request-fields,http-response,response-fields']
operation::{event}/event_cancel_annual_test[snippets='http-request,http-response,curl-request']

=== 당직 취소
// operation::user-controller-test/join_success_test[snippets='http-request,request-fields,http-response,response-fields']
operation::{event}/event_cancel_duty_test[snippets='http-request,http-response,curl-request']

=== 승인된 리스트 가져오기 (모든 이벤트)
operation::{event}/all_event_test[snippets='http-request,http-response,curl-request']

=== 승인된 리스트 가져오기 (연차)
operation::{event}/all_annual_test[snippets='http-request,http-response,curl-request']

=== 승인된 리스트 가져오기 (당직)
operation::{event}/all_duty_test[snippets='http-request,http-response,curl-request']


=== 로그인한 사용자의 연차 리스트 가져오기
operation::{event}/my-annual-list_test[snippets='http-request,http-response']

=== 로그인한 사용자 당직 리스트 가져오기
operation::{event}/my-duty-list_test[snippets='http-request,http-response']



// === 회원상세보기 (권한 없음 실패)
// ===== Request Example
// include::{snippets}/{event}/detail_fail_forbidden_test/http-request[]
//
// ===== Response Example
// include::{snippets}/{event}/detail_fail_forbidden_test/http-response[]
//
// ===== Curl
// include::{snippets}/{event}/detail_fail_forbidden_test/curl-request[]