version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile_Mysql
    container_name: mydb
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: mydb
    ports:
      - 3306:3306

  spring:
    build:
      context: .
      dockerfile: Dockerfile_Spring2
    container_name: myapp
    restart: always
    ports:
      - 8080:5999
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234



