# 베이스 이미지를 선택합니다.
FROM alpine:latest

# 작업 디렉토리를 생성합니다.
WORKDIR /app

# 애플리케이션을 실행할 때 필요한 패키지를 설치합니다.
RUN apk update && \
    apk add openjdk11 && \
    rm -rf /var/cache/apk/*

COPY /build/libs/restend-0.0.1-SNAPSHOT.jar my-app.jar

# 스프링 프로파일을 설정합니다.
ENV aws_access_key AKIAXX6AEBP7WSB3MLU5
ENV aws_secret_key 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
ENV aws_s3_bucket yoseobara-storage
ENV aws_s3_bucket_url https://yoseobara-storage.s3.ap-northeast-2.amazonaws.com

# 애플리케이션을 실행합니다.
CMD ["java", "-jar", "my-app.jar"]
